# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37cf626d5941c671732e90e2825b63dbf0f363447f4a147be48c5d2072de998847b560204978c95063553dce8d555cb6a2ff3491f939174212f9672435556572

test:
  secret_key_base: dd7bf5719691fc471259a2898048f6984ccae9e1a625f88d75213b2322318b8cfbfd8e8760092e6d0d80982d201641dfb8281900145d5770802d0ce8da1c45a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
